# -*- coding: utf-8 -*-
"""speech_to_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-uYIvt4b4VcEjsagGI9efdTyRwNUyGi
"""

# Installer ffmpeg
!sudo apt update
!sudo apt install ffmpeg -y

# Installer les bibliothèques Python nécessaires
!pip install --upgrade pip
!pip install --upgrade transformers datasets[audio] accelerate

import torch
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq, pipeline
from datasets import load_dataset

# Configurer le dispositif (GPU si disponible) et le type de données
device = 0 if torch.cuda.is_available() else -1  # 0 pour le premier GPU, -1 pour CPU
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

# Identifier le modèle
model_id = "openai/whisper-large-v3-turbo"

# Charger le modèle et le processeur
processor = AutoProcessor.from_pretrained(model_id)
model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id,
    torch_dtype=torch_dtype,
    low_cpu_mem_usage=True,
    use_safetensors=True  # Optionnel, améliore la vitesse de chargement
)

# Déplacer le modèle vers le dispositif approprié
if torch.cuda.is_available():
    model.to("cuda")

# Créer le pipeline pour la reconnaissance automatique de la parole
pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    torch_dtype=torch_dtype,
    device=device,  # Utilise GPU si disponible
)

from google.colab import drive
drive.mount('/content/drive')

# Transcrire le fichier audio local téléchargé
result = pipe("Es.mp3", return_timestamps=True)  # Add return_timestamps=True
print("Transcription :", result["text"])

# Enregistrer la transcription dans un fichier texte
with open("Es.mp3", "w", encoding="utf-8") as f:
    f.write(result["text"])

# Télécharger le fichier texte (optionnel)
from google.colab import files
files.download("mon_fichier_final2.txt")